#!/bin/bash
#title			: /etc/update-motd.d/10-version
#description	: This Script will output the linux version
#author			: SHelfinger
#date			: 20160620
#version		: 0.1    
#usage			: bash 10-version OR ./10-version
#notes			: It's colorful, be aware that some apps needs to be installed, see depencies
#bash_version	: 4.3.30(1)-release
#depencies		: Nothing (Normal Installation)
#installation	: chmod +x 10-version | mv 10-version /etc/update-motd.d/10-version
#license		: GPLv3
#==============================================================================
OS=`uname -s`
MACH=`uname -m`

if [ "${OS}" = "SunOS" ] ; then
	OS=Solaris
	ARCH=`uname -p`	
	OSSTR="${OS} ${REV}(${ARCH} `uname -v`)"
elif [ "${OS}" = "AIX" ] ; then
	OSSTR="${OS} `oslevel` (`oslevel -r`)"
elif [ "${OS}" = "Linux" ] ; then
	KERNEL=`uname -r`
	if [ -f /etc/redhat-release ] ; then
		DIST='RedHat'
		PSUEDONAME=`cat /etc/redhat-release | sed s/.*\(// | sed s/\)//`
		REV=`cat /etc/redhat-release | sed s/.*release\ // | sed s/\ .*//`
	elif [ -f /etc/SUSE-release ] ; then
		DIST=`cat /etc/SUSE-release | tr "\n" ' '| sed s/VERSION.*//`
		REV=`cat /etc/SUSE-release | tr "\n" ' ' | sed s/.*=\ //`
	elif [ -f /etc/mandrake-release ] ; then
		DIST='Mandrake'
		PSUEDONAME=`cat /etc/mandrake-release | sed s/.*\(// | sed s/\)//`
		REV=`cat /etc/mandrake-release | sed s/.*release\ // | sed s/\ .*//`
	elif [ -f /etc/debian_version ] ; then
		DIST="Debian \033[1;33m`cat /etc/debian_version`"
		REV=""
        PSUEDONAME=`dpkg --status tzdata|grep Provides|cut -f2 -d'-'`
	fi
	if [ -f /etc/UnitedLinux-release ] ; then
		DIST="${DIST}[`cat /etc/UnitedLinux-release | tr "\n" ' ' | sed s/VERSION.*//`]"
	fi
	OSSTR="\033[1;32m${OS} \033[1;31m${DIST} \033[1;33m${REV}\033[0m(\033[1;34m${PSUEDONAME} \033[1;37m${KERNEL} \033[1;36m${MACH}\033[0m)"
fi
echo -e ${OSSTR}
