#!/bin/bash
#title			: /etc/update-motd.d/50-systop
#description	: This Script will output the Hostname, FQDN, IP
#author			: SHelfinger
#date			: 20160620
#version		: 0.1    
#usage			: bash 50-systop OR ./50-systop
#notes			: It's colorful, be aware that some apps needs to be installed, see depencies
#bash_version	: 4.3.30(1)-release
#depencies		: Nothing (Normal Installation)
#installation	: chmod +x 50-systop | mv 50-systop /etc/update-motd.d/50-systop
#license		: GPLv3
#==============================================================================
LANGUAGE=("\033[01;0mHostname" "\033[01;0mDNS" "\033[01;0mFQDN" "\033[01;0mIP")
INFO=("\033[1;33m$(hostname -s)" "\033[1;34m$(hostname -d)" "\033[1;31m$(hostname -f)" "\033[1;32m$(hostname -i)")
array_size=1

echo -e ${LANGUAGE[0]} ${INFO[0]} ${LANGUAGE[1]} ${INFO[1]} ${LANGUAGE[2]} ${INFO[2]} ${LANGUAGE[3]} ${INFO[3]}
