#!/bin/bash
CURRENT_IP=`last -n 2 $USER | head -n 1 | awk '{print $3}'`
LAST_IP=`last -n 2 $USER | head -n 2 | tail -n1 | awk '{print $3}'`
LAST_DATE=`last -n 2 $USER | head -n 2 | tail -n1 | awk '{ s = ""; for (i = 4; i <= NF; i++) s = s $i " "; print s }' | rev | awk '{ s = ""; for (i = 2; i <= NF; i++) s = s $i " "; print s }' | rev | sed -e 's/^[[:space:]]*//'`

echo -e "\033[0mCurrent IP: \033[1;31m$CURRENT_IP \033[0mLast IP: \033[1;34m$LAST_IP \033[0mLast Access: \033[1;33m$LAST_DATE\033[0m"
