#!/bin/bash
#title			: /etc/update-motd.d/60-lastlogin
#description	: This Script will output the memory information
#author			: SHelfinger
#date			: 20160620
#version		: 0.1    
#usage			: bash 60-lastlogin OR ./60-lastlogin
#notes			: It's colorful, be aware that some apps needs to be installed, see depencies
#bash_version	: 4.3.30(1)-release
#depencies		: rev (sudo apt-get install rev)
#installation	: chmod +x 60-lastlogin | mv 60-lastlogin /etc/update-motd.d/60-lastlogin
#license		: GPLv3
#==============================================================================
REV=$(which rev)
CURRENT_IP=`last -n 2 $USER | head -n 1 | awk '{print $3}'`
LAST_IP=`last -n 2 $USER | head -n 2 | tail -n1 | awk '{print $3}'`
LAST_DATE=`last -n 2 $USER | head -n 2 | tail -n1 | awk '{ s = ""; for (i = 4; i <= NF; i++) s = s $i " "; print s }' | $REV | awk '{ s = ""; for (i = 2; i <= NF; i++) s = s $i " "; print s }' | $REV | sed -e 's/^[[:space:]]*//'`

echo -e "\033[0mCurrent IP: \033[1;31m$CURRENT_IP \033[0mLast IP: \033[1;34m$LAST_IP \033[0mLast Access: \033[1;33m$LAST_DATE\033[0m"
