#!/bin/bash
#title			: /etc/update-motd.d/90-fail2ban
#description	: This Script will output the today's ban statistic from Fail2ban
#author			: SHelfinger
#date			: 20160620
#version		: 0.1    
#usage			: bash 90-fail2ban OR ./90-fail2ban
#notes			: It's colorful, be aware that some apps needs to be installed, see depencies
#bash_version	: 4.3.30(1)-release
#depencies		: fail2ban (sudo apt-get install fail2ban)
#				: crudini (sudo apt-get install crudini)
#installation	: chmod +x 90-fail2ban | mv 90-fail2ban /etc/update-motd.d/90-fail2ban
#license		: MIT
#==============================================================================

#Configuration
# Fail2Ban config file, usually it's jail.conf OR jail.local
JAIL_CONF="/etc/fail2ban/jail.conf"
# Fail2Ban log file, usually /var/log/fail2ban.log
FAIL2BAN_LOG="/var/log/fail2ban.log"
# Maximum Entries in the list, 0 is unlimited
MAX_ENTRIES="10"
# You do NOT need to edit this, script will find crudini!
CRUDINI=$(which crudini)
#Configuration END

echo -en "\033[1;33mFail2Ban \033[1;32mToday's Ban \033[1;31mStatistics\033[0m\n"

grep "Ban " $FAIL2BAN_LOG | grep `date +%Y-%m-%d` | awk -F[\ \:] '{print $10,$8}' | sort | awk '{print "\033[1;33m"$1,$2}' | uniq -c | while read output;
do 
    list=$(echo $output | awk '{ print $1}' | sed -e 's/^[ \t]*//')
    ip=$(echo $output | awk '{ print $2}')
    port=$(echo $output | awk '{ print $3}' | sed 's/\(\[\|\]\)//g')
    
    FAIL2BAN_SSH_BANTIME=`$CRUDINI --get $JAIL_CONF $port maxretry`
    
    if [ "$FAIL2BAN_SSH_BANTIME" -gt "1" ]; then
        maxretry=$FAIL2BAN_SSH_BANTIME
    else 
        maxretry=`$CRUDINI --get $JAIL_CONF default maxretry`
    fi
    if [ "$list" -gt "$maxretry" ]; then
        echo -en $'\t'"\033[1;31m$list"$'\t'
    else 
        echo -en $'\t'"\033[0m$list"$'\t'
    fi
    ok=1
    echo -e "$ip"$'\t'"\033[0m(\033[1;32m$port\033[0m)"
    if [ "$MAX_ENTRIES" -gt "0" ]; then
    	((c++)) && ((c==$MAX_ENTRIES)) && break
    fi
done
if [ "$ok" == "0" ]; then
	echo -en "\033[1;32mNo Ban's today\n"
fi
